# Generated by Django 6.1.1 on 2026-09-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Retail price, USD per gallon",
                        max_digits=8,
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lat", "lon"], name="routeplanne_lat_0c1565_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Normalised city name, see geo.normalize_city",
                        max_length=100,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "state"), name="unique_place_key_state"
                    )
                ],
            },
        ),
    ]
